"""Compatibility exports for OCR handling in core.py."""

from .core import (
    AdaptiveOcrResult,
    OcrEngine,
    OcrRunner,
    RapidOcrEngine,
    binary_variant,
    candidate_from_result,
    candidate_quality,
    classify_line_role,
    classify_row_role,
    cluster_reading_rows,
    enhanced_variant,
    join_ocr_lines,
    meaningful_length,
    otsu_threshold,
    recognize_adaptive,
    sort_reading_order,
    weighted_confidence,
)

__all__ = [
    "AdaptiveOcrResult",
    "OcrEngine",
    "OcrRunner",
    "RapidOcrEngine",
    "binary_variant",
    "candidate_from_result",
    "candidate_quality",
    "classify_line_role",
    "classify_row_role",
    "cluster_reading_rows",
    "enhanced_variant",
    "join_ocr_lines",
    "meaningful_length",
    "otsu_threshold",
    "recognize_adaptive",
    "sort_reading_order",
    "weighted_confidence",
]
